In [1]:
import tensorflow as tf
import numpy as np

In [5]:
t = tf.constant([[1.,2.,3.,],[4.,5.,6.]])

In [4]:
tf.constant([[1.,2.,3.,],[4.,5.,6.]],dtype=tf.float16)

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

In [6]:
t.shape

TensorShape([2, 3])

In [7]:
t.dtype

tf.float32

In [15]:
t[:,1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [16]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [17]:
t/2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]], dtype=float32)>

In [20]:
tf.sqrt(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)>

In [21]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [23]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [24]:
a = t.numpy()

In [25]:
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [26]:
tf.square(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [27]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [29]:
t[1,0]=6

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [30]:
tV = tf.Variable(t)

In [31]:
tV

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [34]:
tV[0,1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 1., 42.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)>

In [35]:
tV.scatter_nd_update(indices=[[0,0],[1,2]],updates=[100.,200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   3.],
       [  4.,   5., 200.]], dtype=float32)>